version: "3.8"

services:
  linkedin-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brainsait-linkedin-automation
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/brainsait-linkedin
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./sessions:/app/sessions
      - ./profiles:/app/profiles
    depends_on:
      - mongo
      - redis
      - influxdb
    networks:
      - brainsait-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          cpus: "1"
          memory: 2G

  mongo:
    image: mongo:6
    container_name: linkedin-mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - brainsait-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: linkedin-redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - brainsait-network
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: linkedin-metrics
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=brainsait
      - DOCKER_INFLUXDB_INIT_BUCKET=linkedin
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    networks:
      - brainsait-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: linkedin-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - linkedin-engine
    networks:
      - brainsait-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  influxdb_data:
    driver: local

networks:
  brainsait-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
